# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("quotes_dataset.csv")

print("First 5 Rows:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

plt.figure(figsize=(8,5))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values Heatmap")
plt.show()

print("\nStatistical Summary:")
print(df.describe(include='all'))

print("\nSample Questions:")
print("1. Which category appears most frequently?")
print("2. Are there missing values?")
print("3. What patterns exist in the dataset?")
print("4. Are there any unusual observations?")


print("\nDuplicate Rows:", df.duplicated().sum())


num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True)
    plt.title(f"Distribution of {col}")
    plt.show()


if len(num_cols) > 1:
    plt.figure(figsize=(8,6))
    sns.heatmap(df[num_cols].corr(),
                annot=True,
                cmap="coolwarm")
    plt.title("Correlation Matrix")
    plt.show()


for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=df[col])
    plt.title(f"Outlier Detection - {col}")
    plt.show()

from scipy.stats import ttest_ind

if len(num_cols) > 0:
    col = num_cols[0]

    median_value = df[col].median()

    group1 = df[df[col] <= median_value][col]
    group2 = df[df[col] > median_value][col]

    t_stat, p_value = ttest_ind(group1, group2)

    print("\nHypothesis Testing")
    print("T-statistic:", t_stat)
    print("P-value:", p_value)

    if p_value < 0.05:
        print("Significant Difference Found")
    else:
        print("No Significant Difference Found")


print("\nData Quality Report")
print("-------------------")
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

print("\nEDA Completed Successfully!")